name: SecondSite
favicon: null
layout_spectrum: 0.57159
typography_spectrum: 0.59987
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c3c3c3'
    - '#ababab'
    - '#242424'
    - '#6f6f6f'
    - '#3e3e3e'
  brandStrength: 0.5776166475843638
  lightness: 0.9300407636910677
  saturation: 0.9581360097508878
  rhythmicContrast: 0.5104877494741231
purpose: []
