layout_spectrum: 0.57159
favicon: null
name: SecondSite
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.6652614
  lightness: 0.9300407636910677
  saturation: 0.9581360097508878
  rhythmicContrast: 0.5104877494741231
  brandColors:
    - '#030D03'
    - '#E0FABD'
    - '#1F3A2E'
    - '#9BC4A2'
    - '#78A26E'
typography_spectrum: 0.59987
