name: SecondSite
favicon: null
layout_spectrum: 0.8937704539857805
typography_spectrum: 0.1470549099612981
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5776166475843638
  lightness: 0.9300407636910677
  saturation: 0.9581360097508878
  rhythmicContrast: 0.5104877494741231
purpose: []
