layout_spectrum: 0.57159
favicon: null
name: SecondSite
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.4915683
  lightness: 0.9300407636910677
  saturation: 0.9581360097508878
  rhythmicContrast: 0.5104877494741231
  brandColors:
    - '#657899'
    - '#4B5B77'
    - '#D7D8E0'
    - '#907977'
    - '#01010D'
typography_spectrum: 0.59987
